### Variáveis
@prod_url = https://weather-api-nccto6oxnq-uc.a.run.app

### Health Check (Local)
GET http://localhost:8080/health HTTP/1.1

### Health Check (Prod)
GET {{prod_url}}/health HTTP/1.1

### Get weather for valid zipcode (Local)
GET http://localhost:8080/weather/01310100 HTTP/1.1

### Get weather for valid zipcode (Prod)
GET {{prod_url}}/weather/88303410 HTTP/1.1

### Get weather for invalid format zipcode (422)
GET http://localhost:8080/weather/123 HTTP/1.1

### Get weather for zipcode not found (404)
GET http://localhost:8080/weather/99999999 HTTP/1.1
